# Este script es utilizado para crear un entorno de integracion continua y despliegue continuo (CI/CD)

name: Python CI/CD pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2.3.3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        with:
          author_name: "Action"
          fields: repo,message,commit,author,action,eventName
