name: Hola mundo

on:
  push:
    branches:
      - dev
      
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Hola Mundo
       run: echo "Hola Mundo"

  other:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
     - name: LS
       run: ls -al